% MATLAB Editor Run Commands
% @version 4
% It is recommended that you do not edit this file directly, but use the
% Run button. Changes made to comments that exist outside of a
% configuration will not be saved.

%% @name k_nn
%  @associatedFile /MATLAB Drive/knn/k_nn.m
%  @mostRecentlyActioned true
%  @uniqueId 095675FE

k_nn

%% @name Yazdir
%  @associatedFile /MATLAB Drive/knn/Yazdir.m
%  @mostRecentlyActioned true
%  @uniqueId 3612EF21

Yazdir

%% @name problem
%  @associatedFile /MATLAB Drive/knn/afdb/problem.m
%  @mostRecentlyActioned true
%  @uniqueId 8B9B6B46

problem

%% @name chaos
%  @associatedFile /MATLAB Drive/knn/afdb/chaos.m
%  @mostRecentlyActioned true
%  @uniqueId 78D9F24D

chaos

%% @name SingerMap_Reverse
%  @associatedFile /MATLAB Drive/knn/afdb/SingerMap_Reverse.m
%  @mostRecentlyActioned true
%  @uniqueId 41528899

SingerMap_Reverse

%% @name Sigmoid_Func_1_Increase
%  @associatedFile /MATLAB Drive/knn/afdb/Sigmoid_Func_1_Increase.m
%  @mostRecentlyActioned true
%  @uniqueId D3F03BE5

Sigmoid_Func_1_Increase

%% @name case_1
%  @associatedFile /MATLAB Drive/knn/afdb/case_1.m
%  @mostRecentlyActioned true
%  @uniqueId EDCEB846

case_1

%% @name knn
%  @associatedFile /MATLAB Drive/knn/knn.m
%  @mostRecentlyActioned true
%  @uniqueId DC9666F8

knn

%% @name Verileri_Oku
%  @associatedFile /MATLAB Drive/knn/Verileri_Oku.m
%  @mostRecentlyActioned true
%  @uniqueId 8CE01CB0

Verileri_Oku

%% @name Mfro_007
%  @associatedFile /MATLAB Drive/Mfro_007.m
%  @mostRecentlyActioned true
%  @uniqueId 93623249

Mfro_007

%% @name readData
%  @associatedFile /MATLAB Drive/readData.m
%  @mostRecentlyActioned true
%  @uniqueId 2240A671

readData

%% @name mrfo
%  @associatedFile /MATLAB Drive/mrfo.m
%  @mostRecentlyActioned true
%  @uniqueId 46920FDB

mrfo

%% @name case_1
%  @associatedFile /MATLAB Drive/case_1.m
%  @mostRecentlyActioned true
%  @uniqueId 56B3BAED

case_1

%% @name problem_terminate
%  @associatedFile /MATLAB Drive/problem_terminate.m
%  @mostRecentlyActioned true
%  @uniqueId D4720065

problem_terminate

%% @name boyut_azaltma
%  @associatedFile /MATLAB Drive/boyut_azaltma.m
%  @mostRecentlyActioned true
%  @uniqueId A2230237

boyut_azaltma

%% @name Verileri_Oku
%  @associatedFile /MATLAB Drive/Verileri_Oku.m
%  @mostRecentlyActioned true
%  @uniqueId 12C7147C

Verileri_Oku

%% @name problem
%  @associatedFile /MATLAB Drive/problem.m
%  @mostRecentlyActioned true
%  @uniqueId 6AB9ED35

problem

